name: Pull Request
on:
  pull_request:

jobs:
  build-rocks:
    name: Build Rocks
    uses: ./.github/workflows/build_rock.yaml
    with:
      working-directory: cilium-operator-generic
      trivy-image-config: "trivy.yaml"
